# Generated by Django 3.0.3 on 2020-07-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_monitoring_app', '0004_auto_20200714_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='phone_no',
            field=models.IntegerField(default=0),
        ),
    ]
